import { MealItem } from "../types";

export const DEFAULT_MEALS: MealItem[] = [
  // Monday
  {
    id: "Monday-breakfast",
    day: "Monday",
    mealType: "breakfast",
    menuName: "โจ๊กอกไก่ใส่ขิงอ่อนและไข่ลวก",
    calories: 220,
    description: "โจ๊กข้าวหอมมะลิบดละเอียด ท็อปปิ้งอกไก่ฉีก ขิงซอยละเอียด และไข่ลวก ย่อยง่าย เหมาะสำหรับกระตุ้นระบบเผาผลาญยามเช้า",
    status: "planned",
  },
  {
    id: "Monday-lunch",
    day: "Monday",
    mealType: "lunch",
    menuName: "ข้าวมันอกไก่ต้มน้ำจิ้มแจ่วสมุนไพร",
    calories: 380,
    description: "ข้าวกล้องหอมมะลิหุงแบบข้าวมันสุขภาพ อกไก่ต้มไม่ติดหนัง เสิร์ฟคู่แตงกวาและน้ำจิ้มแจ่วสมุนไพรลดโซเดียม",
    status: "planned",
  },
  {
    id: "Monday-dinner",
    day: "Monday",
    mealType: "dinner",
    menuName: "แกงจืดเต้าหู้หมูสับสาหร่ายวากาเมะ",
    calories: 180,
    description: "ซุปใสเต้าหู้ไข่ หมูสับไร้มัน ปั้นก้อนกลม ใส่สาหร่ายวากาเมะและผักกาดขาว ซุปร้อนๆ สบายท้องแคลอรีต่ำก่อนนอน",
    status: "planned",
  },

  // Tuesday
  {
    id: "Tuesday-breakfast",
    day: "Tuesday",
    mealType: "breakfast",
    menuName: "แซนด์วิชโฮลวีทอกไก่รมควันและอโวคาโด",
    calories: 290,
    description: "ขนมปังโฮลวีทปิ้ง สอดไส้อกไก่รมควันเนื้อนุ่ม ผักสลัด และอโวคาโดบด ไขมันดีจากอโวคาโดช่วยให้อิ่มนานและดีต่อสมอง",
    status: "planned",
  },
  {
    id: "Tuesday-lunch",
    day: "Tuesday",
    mealType: "lunch",
    menuName: "สปาเกตตี้โฮลวีทผัดพริกแห้งทูน่าในน้ำแร่",
    calories: 420,
    description: "เส้นสปาเกตตี้โฮลวีทเหนียวนุ่ม ผัดสมุนไพร พริกแห้ง กระเทียม และทูน่า แคลอรีพอดี ได้สารอาหารคาร์บเชิงซ้อนครบถ้วน",
    status: "planned",
  },
  {
    id: "Tuesday-dinner",
    day: "Tuesday",
    mealType: "dinner",
    menuName: "ปลากะพงนึ่งซีอิ๊วญี่ปุ่นพร้อมผักลวกหวาน",
    calories: 210,
    description: "เนื้อปลากะพงสดๆ นึ่งร้อนๆ ราดซอสซีอิ๊วญี่ปุ่นรสเค็มหวานบางเบา แนมด้วยบลอกโคลีและแครอทลวกสุก ย่อยง่ายมาก",
    status: "planned",
  },

  // Wednesday
  {
    id: "Wednesday-breakfast",
    day: "Wednesday",
    mealType: "breakfast",
    menuName: "ไข่ตุ๋นทรงเครื่องกุ้งสดข้าวกล้อง",
    calories: 250,
    description: "ไข่ตุ๋นนมสดเนื้อเนียนนุ่ม ท็อปด้วยกุ้งสับ แครอทเต๋า ต้นหอม ทานคู่ข้าวกล้องร้อนๆ อิ่มเบาสบาย แหล่งโปรตีนพรีเมียม",
    status: "planned",
  },
  {
    id: "Wednesday-lunch",
    day: "Wednesday",
    mealType: "lunch",
    menuName: "ลาบอกไก่สับข้าวคั่วข้าวไรซ์เบอร์รี่",
    calories: 390,
    description: "ลาบอกไก่สับปรุงรสเปรี้ยวเค็มเผ็ดพอดี โรยผักชีฝรั่งสะระแหน่ ทานคู่ข้าวไรซ์เบอร์รี่ แซ่บสไตล์คลีนแบบไม่มีไขมันส่วนเกิน",
    status: "planned",
  },
  {
    id: "Wednesday-dinner",
    day: "Wednesday",
    mealType: "dinner",
    menuName: "ต้มยำน้ำใสอกไก่ใส่เห็ดออรินจิ",
    calories: 160,
    description: "ต้มยำน้ำใสรสเด็ดหอมสมุนไพรข่า ตะไคร้ ใบมะกรูด ใส่อกไก่หั่นเต๋าและเห็ดออรินจิ ซดร้อนๆ คล่องคอ กระตุ้นระบบย่อยอาหาร",
    status: "planned",
  },

  // Thursday
  {
    id: "Thursday-breakfast",
    day: "Thursday",
    mealType: "breakfast",
    menuName: "กรีกโยเกิร์ตท็อปปิ้งเบอร์รี่รวมและน้ำผึ้ง",
    calories: 210,
    description: "กรีกโยเกิร์ตเข้มข้นโปรตีนสูง ท็อปด้วยสตรอว์เบอร์รี่ บลูเบอร์รี่สด และราดน้ำผึ้งป่าแท้บางๆ อร่อยสดชื่นกระปรี้กระเปร่า",
    status: "planned",
  },
  {
    id: "Thursday-lunch",
    day: "Thursday",
    mealType: "lunch",
    menuName: "ข้าวผัดกุ้งบลอกโคลีและแครอท",
    calories: 400,
    description: "ข้าวผัดไข่สไตล์จีนไม่ใส่น้ำมันเยิ้ม ใส่กุ้งสดเด้ง บลอกโคลีหวานกรอบ และแครอท เพิ่มใยอาหารและโปรตีนชั้นเลิศ",
    status: "planned",
  },
  {
    id: "Thursday-dinner",
    day: "Thursday",
    mealType: "dinner",
    menuName: "ยำวุ้นเส้นโบราณใส่อกไก่สับและไข่ต้ม",
    calories: 230,
    description: "ยำวุ้นเส้นรสกลมกล่อม ใส่อกไก่ฉีกและผักยำ มะเขือเทศ หอมใหญ่ เคียงด้วยไข่ต้มยางมะตูม 1 ฟอง อิ่มอร่อยและไม่หนักท้อง",
    status: "planned",
  },

  // Friday
  {
    id: "Friday-breakfast",
    day: "Friday",
    mealType: "breakfast",
    menuName: "ข้าวต้มปลากะพงโรยกระเทียมเจียวสุขภาพ",
    calories: 240,
    description: "ข้าวต้มน้ำซุปผักกลมกล่อม ใส่เนื้อปลากะพงชิ้นโตสดหวาน โรยขิงแก่ ผักชี และกระเทียมเจียวในน้ำมันรำข้าวเจียวเอง",
    status: "planned",
  },
  {
    id: "Friday-lunch",
    day: "Friday",
    mealType: "lunch",
    menuName: "สลัดอกไก่ย่างถ่านน้ำสลัดงาญี่ปุ่น",
    calories: 380,
    description: "อกไก่หมักสมุนไพรย่างจนหอมหั่นชิ้น วางบนผักสลัดกรอบคอส แครด เรดโอ๊ค ราดน้ำสลัดงาซีอิ๊วญี่ปุ่นสไตล์รักสุขภาพ",
    status: "planned",
  },
  {
    id: "Friday-dinner",
    day: "Friday",
    mealType: "dinner",
    menuName: "เต้าหู้ขาวทรงเครื่องหมูสับผัดซอสเบา",
    calories: 190,
    description: "เต้าหู้ขาวเนื้อนุ่มนึ่ง ท็อปด้วยซอสผัดหมูสับเต้าเจี้ยว ถั่วลันเตา แครอทเต๋า อร่อยละมุนและเต็มเปี่ยมไปด้วยโปรตีนพืช",
    status: "planned",
  },

  // Saturday
  {
    id: "Saturday-breakfast",
    day: "Saturday",
    mealType: "breakfast",
    menuName: "ไข่กะทะคลีน 2 ฟองท็อปปิ้งผักรวม",
    calories: 190,
    description: "ไข่ดาว 2 ฟองปรุงบนกระทะเทฟลอนไม่ใช้น้ำมัน ตกแต่งด้วยกุนเชียงปลาอบแห้ง อกไก่สับ ถั่วลันเตา และพริกไทยดำป่น",
    status: "planned",
  },
  {
    id: "Saturday-lunch",
    day: "Saturday",
    mealType: "lunch",
    menuName: "สเต็กอกไก่พริกไทยดำกะทะร้อนและมันบด",
    calories: 410,
    description: "อกไก่ชิ้นโตหมักพริกไทยดำนุ่มๆ ย่างสุกกำลังดี เสิร์ฟคู่บลอกโคลีย่าง และมันฝรั่งอบบดไร้นมเนยไขมันสูง",
    status: "planned",
  },
  {
    id: "Saturday-dinner",
    day: "Saturday",
    mealType: "dinner",
    menuName: "ซุปมะระยัดไส้ไก่สับใส่วุ้นเส้น",
    calories: 160,
    description: "มะระจีนหั่นแว่นตุ๋นจนนุ่มลดขม ยัดไส้ไก่สับผสมกระเทียมพริกไทย วุ้นเส้นซุปร้อนๆ ช่วยล้างสารพิษและนอนหลับสนิท",
    status: "planned",
  },

  // Sunday
  {
    id: "Sunday-breakfast",
    day: "Sunday",
    mealType: "breakfast",
    menuName: "แพนเค้กข้าวโอ๊ตกล้วยหอมและโยเกิร์ตสด",
    calories: 260,
    description: "แพนเค้กคลีนทำจากกล้วยหอมบดละเอียด ผสมข้าวโอ๊ตและไข่ไก่ ทอดกระทะแบน เสิร์ฟเคียงกรีกโยเกิร์ตและสตรอว์เบอร์รี่สด",
    status: "planned",
  },
  {
    id: "Sunday-lunch",
    day: "Sunday",
    mealType: "lunch",
    menuName: "แกงส้มชะอมชุบไข่ทอดทูน่าผักรวม",
    calories: 350,
    description: "แกงส้มน้ำใสรสมะขามเปียกสุดแซ่บ ชะอมชุบไข่ทอดเตาอบลดน้ำมัน ทูน่าป่นเข้มข้น และยอดผักบุ้งกะหล่ำปลี ทานคู่ข้าวกล้อง",
    status: "planned",
  },
  {
    id: "Sunday-dinner",
    day: "Sunday",
    mealType: "dinner",
    menuName: "สุกี้น้ำอกไก่ฉีกใส่วุ้นเส้นและผักล้นกระทะ",
    calories: 220,
    description: "สุกี้ต้มใส่ออกไก่นุ่ม ผักกาดขาว ผักบุ้งคัดอ่อน วุ้นเส้นญี่ปุ่น และน้ำจิ้มสุกี้สูตรเด็ดลดโซเดียม 1 ช้อนโต๊ะ รสชาติอบอุ่นกลมกล่อม",
    status: "planned",
  },
];
